sam templates

diff --git a/bin/cfn/ddb_deploy b/bin/cfn/ddb_deploy
--- a/bin/cfn/ddb_deploy
+++ b/bin/cfn/ddb_deploy
@@ -1,24 +1,40 @@
-#! /bin/bash
+#! /usr/bin/env bash
+set -e # stop the execution of the script if it fails
 
-set -e # stop execution if anything fails
-
-
-CFN_PATH="/workspaces/aws-bootcamp-cruddur-2023/aws/cfn/ddb/template.yaml"
+FUNC_DIR="/workspaces/aws-bootcamp-cruddur-2023/ddb/cruddur-messaging-stream/"
+TEMPLATE_PATH="/workspaces/aws-bootcamp-cruddur-2023/aws/cfn/ddb/template.yaml"
 CONFIG_PATH="/workspaces/aws-bootcamp-cruddur-2023/aws/cfn/ddb/config.toml"
-cfn-lint $CFN_PATH
 
-BUCKET=$(cfn-toml key deploy.bucket -t $CONFIG_PATH)
-REGION=$(cfn-toml key deploy.region -t $CONFIG_PATH)
-STACK_NAME=$(cfn-toml key deploy.stack_name -t $CONFIG_PATH)
-PARAMETERS=$(cfn-toml params v2 -t $CONFIG_PATH)
+sam validate -t $TEMPLATE_PATH
+
+echo "== build"
+# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-build.html
+# --use-container
+# use container is for building the lambda in a container
+# it's still using the runtimes and its not a custom runtime
+sam build \
+--use-container \
+--config-file $CONFIG_PATH \
+--template $TEMPLATE_PATH \
+--base-dir $FUNC_DIR
+#--parameter-overrides
+
+TEMPLATE_PATH='/workspaces/aws-bootcamp-cruddur-2023/.aws-sam/build/template.yaml'
+OUTPUT_TEMP_PATH='/workspaces/aws-bootcamp-cruddur-2023/.aws-sam/build/packaged.yaml'
 
 
-aws cloudformation deploy \
-    --stack-name $STACK_NAME \
-    --s3-bucket $BUCKET \
-    --region $REGION \
-    --parameter-overrides $PARAMETERS \
-    --template-file $CFN_PATH \
-    --no-execute-changeset \
-    --tags group=cruddur-ddb \
-    --capabilities CAPABILITY_NAMED_IAM
+sam package \
+--s3-bucket "cfn-artifacts-sda" \
+--config-file $CONFIG_PATH \
+--output-template-file $OUTPUT_TEMP_PATH \
+--s3-prefix "ddb"
+--template-file $TEMPLATE_PATH
+# sam deploy
+
+
+sam deploy \
+    --template-file $OUTPUT_TEMP_PATH \
+    --stack-name "CrdDdb" \
+    --config_file $CONFIG_PATH \
+    --tags = group=cruddur-ddb \
+    --capabilities CAPABILITY_IAM
